# Generated by Django 5.0.6 on 2024-07-05 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_topic_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
    ]
