# Generated by Django 5.0.3 on 2024-07-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
